INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','01- Abrotanum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','02- Aceticum acidum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','03- Aconitum napellus');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','04- Actea racemosa');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','05- Aesculus hippocastanum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','06- Aethusa cynapium');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','07- Agaricus muscarius');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','08- Agnus castus');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','09- Ailanthus glandulosa');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','10- Allium cepa');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','11- Aloe');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','12- Alumen');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','13- Alumina');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','14- Ambra grisea');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','15- Ammonium carbonicum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','16- Ammonium muriaticum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','17- Anacardium orientale');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','18- Antimonium crudum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','19- Antimonium tartaricum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','20- Apis mellifica');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','21- Apocynum cannabinum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','22- Argentum metallicum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','23- Argentum nitricum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','24- Arnica montana');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','25- Arsenicum album');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','26- Arsenicum iodatum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','27- Arum triphyllum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','28- Asa foetida');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','29- Aurum metallicum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','30- Aurum muriaticum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','31- Baptisia');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','32- Baryta carbonica');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','33- Baryta muriatica');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','34- Belladonna');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','35- Benzoicum acidum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','36- Berberis');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','37- Borax');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','38- Bromium');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','39- Bryonia');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','40- Bufo');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','41- Cactus grandiflorus');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','42- Cadmium sulfuricum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','43- Caladium');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','44- Calcarea arsenicosa');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','45- Calcarea carbonica');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','46- Calcarea fluorica');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','47- Calcarea phosphorica');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','48- Calcarea sulfurica');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','49- Camphora');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','50- Cannabis indica');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','51- Cannabis sativa');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','52- Cantharis');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','53- Capsicum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','54- Carbo animalis');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','55- Carbo vegetabilis');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','56- Carboneum sulfuratum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','57- Carduus marianus');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','58- Causticum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','59- Chamomilla');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','60- Chelidonium');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','61- Chininum arsenicosum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','61- Cicuta virosa');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','63- Cina');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','64- Cinchona (China)');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','65- Cinnabaris');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','66- Cistus canadensis');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','67- Clematis erecta');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','68- Cocculus indicus');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','69- Coccus cacti');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','70- Coffea');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','71- Colchicum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','72- Colocynthis');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','73- Conium maculatum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','74- Crotalus horridus');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','75- Croton tiglium');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','76- Cuprum metallicum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','77- Cyclamen');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','78- Digitalis');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','79- Drosera rotundifolia');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','80- Dulcamara');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','81- Eupatorium perfoliatum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','82- Euphrasia');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','83- Ferrum metallicum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','84- Ferrum phosphoricum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','85- Fluoricum acidum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','86- Gelsemium');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','87- Glonoinum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','88- Graphites');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','89- Gratiola');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','90- Guaiacum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','91- Helleborus niger');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','92- Hepar sulfuris calcareum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','93- Hydrastis canadensis');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','94- Hyoscyamus');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','95- Hypericum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','96- Ignatia');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','97- Iodum (Iodine)');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','98- Ipecacuanha');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','99- Kalium bichromicum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','100- Kalium carbonicum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','101- Kalium iodatum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','102- Kalium phosphoricum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','103- Kalium sulfuricum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','104- Kalmia');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','105- Kreosotum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','106- Lac caninum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','107- Lac vaccinum defloratum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','108- Lachesis');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','109- Laurocerasus');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','110- Ledum palustre');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','111- Lillium tigrinum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','112- Lycopodium');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','113- Magnesia carbonica');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','114- Magnesia muriatica');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','115- Magnesia phosphorica');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','116- Manganum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','117- Medorrhinum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','118- Mercurius');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','119- Mercurius corrosivus');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','120- Mercurius cyanatus');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','121- Mercurius iodatus flavus');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','122- Mercurius iodatus ruber');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','123- Mercurius sulphuricus');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','124- Mezereum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','125- Millefolium');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','126- Moschus');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','127- Muriaticum acidum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','128- Naja');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','129- Natrum arsenicosum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','130- Natrum carbonicum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','131- Natrum muriaticum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','132- Natrum phosphoricum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','133- Natrum sulfuricum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','134- Nitricum acidum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','135- Nux moschata');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','136- Nux vomica');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','137- Opium');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','138- Oxalicum acidum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','139- Petroleum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','140- Phosphoricum acidum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','141- Phosphorus');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','142- Phytolacca');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','143- Picricum acidum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','144- Platina');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','145- Plumbum metallicum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','146- Podophyllum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','147- Psorinum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','148- Pulsatilla');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','149- Pyrogenium');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','150- Ranunculus bulbosus');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','151- Rhododendron');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','152- Rhus toxicodendron');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','153- Rumex crispus');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','154- Ruta graveolens');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','155- Sabadilla');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','156- Sabina');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','157- Sanguinaria');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','158- Sarsaparilla');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','159- Secale cornutum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','160- Selenium');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','161- Senecio aureus');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','162- Senega');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','163- Sepia');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','164- Silicea');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','165- Spigelia anthelmia');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','166- Spongia tosta');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','167- Squilla');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','168- Stannum metallicum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','169- Staphysagria');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','170- Stramonium');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','171- Sulfur');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','172- Sulfuricum acidum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','173- Syphillinum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','174- Tarentula hispana');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','175- Theridion');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','176- Thuya occidentalis');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','177- Tuberculinum bovinum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','178- Valeriana');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','179- Veratrum album');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Homeopathy','Kent Remedies','180- Zincum metallicum');
