INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','01- Abrotanum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','02- Aceticum acidum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','03- Aconitum napellus');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','04- Actea racemosa');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','05- Aesculus hippocastanum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','06- Aethusa cynapium');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','07- Agaricus muscarius');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','08- Agnus castus');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','09- Ailanthus glandulosa');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','10- Allium cepa');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','11- Aloe');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','12- Alumen');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','13- Alumina');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','14- Ambra grisea');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','15- Ammonium carbonicum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','16- Ammonium muriaticum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','17- Anacardium orientale');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','18- Antimonium crudum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','19- Antimonium tartaricum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','20- Apis mellifica');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','21- Apocynum cannabinum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','22- Argentum metallicum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','23- Argentum nitricum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','24- Arnica montana');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','25- Arsenicum album');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','26- Arsenicum iodatum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','27- Arum triphyllum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','28- Asa foetida');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','29- Aurum metallicum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','30- Aurum muriaticum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','31- Baptisia');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','32- Baryta carbonica');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','33- Baryta muriatica');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','34- Belladonna');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','35- Benzoicum acidum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','36- Berberis');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','37- Borax');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','38- Bromium');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','39- Bryonia');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','40- Bufo');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','41- Cactus grandiflorus');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','42- Cadmium sulfuricum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','43- Caladium');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','44- Calcarea arsenicosa');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','45- Calcarea carbonica');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','46- Calcarea fluorica');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','47- Calcarea phosphorica');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','48- Calcarea sulfurica');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','49- Camphora');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','50- Cannabis indica');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','51- Cannabis sativa');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','52- Cantharis');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','53- Capsicum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','54- Carbo animalis');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','55- Carbo vegetabilis');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','56- Carboneum sulfuratum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','57- Carduus marianus');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','58- Causticum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','59- Chamomilla');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','60- Chelidonium');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','61- Chininum arsenicosum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','61- Cicuta virosa');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','63- Cina');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','64- Cinchona (China)');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','65- Cinnabaris');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','66- Cistus canadensis');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','67- Clematis erecta');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','68- Cocculus indicus');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','69- Coccus cacti');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','70- Coffea');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','71- Colchicum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','72- Colocynthis');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','73- Conium maculatum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','74- Crotalus horridus');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','75- Croton tiglium');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','76- Cuprum metallicum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','77- Cyclamen');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','78- Digitalis');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','79- Drosera rotundifolia');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','80- Dulcamara');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','81- Eupatorium perfoliatum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','82- Euphrasia');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','83- Ferrum metallicum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','84- Ferrum phosphoricum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','85- Fluoricum acidum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','86- Gelsemium');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','87- Glonoinum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','88- Graphites');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','89- Gratiola');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','90- Guaiacum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','91- Helleborus niger');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','92- Hepar sulfuris calcareum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','93- Hydrastis canadensis');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','94- Hyoscyamus');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','95- Hypericum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','96- Ignatia');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','97- Iodum (Iodine)');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','98- Ipecacuanha');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','99- Kalium bichromicum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','100- Kalium carbonicum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','101- Kalium iodatum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','102- Kalium phosphoricum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','103- Kalium sulfuricum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','104- Kalmia');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','105- Kreosotum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','106- Lac caninum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','107- Lac vaccinum defloratum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','108- Lachesis');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','109- Laurocerasus');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','110- Ledum palustre');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','111- Lillium tigrinum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','112- Lycopodium');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','113- Magnesia carbonica');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','114- Magnesia muriatica');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','115- Magnesia phosphorica');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','116- Manganum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','117- Medorrhinum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','118- Mercurius');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','119- Mercurius corrosivus');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','120- Mercurius cyanatus');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','121- Mercurius iodatus flavus');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','122- Mercurius iodatus ruber');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','123- Mercurius sulphuricus');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','124- Mezereum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','125- Millefolium');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','126- Moschus');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','127- Muriaticum acidum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','128- Naja');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','129- Natrum arsenicosum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','130- Natrum carbonicum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','131- Natrum muriaticum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','132- Natrum phosphoricum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','133- Natrum sulfuricum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','134- Nitricum acidum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','135- Nux moschata');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','136- Nux vomica');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','137- Opium');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','138- Oxalicum acidum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','139- Petroleum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','140- Phosphoricum acidum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','141- Phosphorus');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','142- Phytolacca');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','143- Picricum acidum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','144- Platina');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','145- Plumbum metallicum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','146- Podophyllum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','147- Psorinum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','148- Pulsatilla');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','149- Pyrogenium');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','150- Ranunculus bulbosus');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','151- Rhododendron');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','152- Rhus toxicodendron');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','153- Rumex crispus');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','154- Ruta graveolens');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','155- Sabadilla');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','156- Sabina');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','157- Sanguinaria');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','158- Sarsaparilla');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','159- Secale cornutum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','160- Selenium');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','161- Senecio aureus');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','162- Senega');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','163- Sepia');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','164- Silicea');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','165- Spigelia anthelmia');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','166- Spongia tosta');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','167- Squilla');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','168- Stannum metallicum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','169- Staphysagria');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','170- Stramonium');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','171- Sulfur');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','172- Sulfuricum acidum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','173- Syphillinum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','174- Tarentula hispana');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','175- Theridion');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','176- Thuya occidentalis');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','177- Tuberculinum bovinum');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','178- Valeriana');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','179- Veratrum album');
INSERT INTO RATE (SOURCE_NAME,GROUP_NAME,NAME) VALUES('Kent Remedies','Homeopathy','180- Zincum metallicum');
